/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.github.jasonqjc.atlas_v2_client;

//import java.text.FieldPosition;
//import java.util.Date;
//
//import com.fasterxml.jackson.databind.util.ISO8601DateFormat;
//import com.fasterxml.jackson.databind.util.ISO8601Utils;
//
//
//public class RFC3339DateFormat extends ISO8601DateFormat {
//
//  // Same as ISO8601DateFormat but serializing milliseconds.
//  @Override
//  public StringBuffer format(Date date, StringBuffer toAppendTo, FieldPosition fieldPosition) {
//    String value = ISO8601Utils.format(date, true);
//    toAppendTo.append(value);
//    return toAppendTo;
//  }
//
//}