/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Structure of v2 entity audit event
 */
@Schema(description = "Structure of v2 entity audit event")

public class JsonEntityAuditEventV2 {
  @JsonProperty("action")
  private JsonEntityAuditActionV2 action = null;

  @JsonProperty("details")
  private String details = null;

  @JsonProperty("entity")
  private JsonAtlasEntity entity = null;

  @JsonProperty("entityId")
  private String entityId = null;

  @JsonProperty("eventKey")
  private String eventKey = null;

  @JsonProperty("timestamp")
  private Long timestamp = null;

  @JsonProperty("type")
  private JsonEntityAuditType type = null;

  @JsonProperty("user")
  private String user = null;

  public JsonEntityAuditEventV2 action(JsonEntityAuditActionV2 action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @Schema(description = "")
  public JsonEntityAuditActionV2 getAction() {
    return action;
  }

  public void setAction(JsonEntityAuditActionV2 action) {
    this.action = action;
  }

  public JsonEntityAuditEventV2 details(String details) {
    this.details = details;
    return this;
  }

   /**
   * Get details
   * @return details
  **/
  @Schema(description = "")
  public String getDetails() {
    return details;
  }

  public void setDetails(String details) {
    this.details = details;
  }

  public JsonEntityAuditEventV2 entity(JsonAtlasEntity entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @Schema(description = "")
  public JsonAtlasEntity getEntity() {
    return entity;
  }

  public void setEntity(JsonAtlasEntity entity) {
    this.entity = entity;
  }

  public JsonEntityAuditEventV2 entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @Schema(description = "")
  public String getEntityId() {
    return entityId;
  }

  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }

  public JsonEntityAuditEventV2 eventKey(String eventKey) {
    this.eventKey = eventKey;
    return this;
  }

   /**
   * Get eventKey
   * @return eventKey
  **/
  @Schema(description = "")
  public String getEventKey() {
    return eventKey;
  }

  public void setEventKey(String eventKey) {
    this.eventKey = eventKey;
  }

  public JsonEntityAuditEventV2 timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @Schema(description = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }

  public JsonEntityAuditEventV2 type(JsonEntityAuditType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public JsonEntityAuditType getType() {
    return type;
  }

  public void setType(JsonEntityAuditType type) {
    this.type = type;
  }

  public JsonEntityAuditEventV2 user(String user) {
    this.user = user;
    return this;
  }

   /**
   * Get user
   * @return user
  **/
  @Schema(description = "")
  public String getUser() {
    return user;
  }

  public void setUser(String user) {
    this.user = user;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonEntityAuditEventV2 jsonEntityAuditEventV2 = (JsonEntityAuditEventV2) o;
    return Objects.equals(this.action, jsonEntityAuditEventV2.action) &&
        Objects.equals(this.details, jsonEntityAuditEventV2.details) &&
        Objects.equals(this.entity, jsonEntityAuditEventV2.entity) &&
        Objects.equals(this.entityId, jsonEntityAuditEventV2.entityId) &&
        Objects.equals(this.eventKey, jsonEntityAuditEventV2.eventKey) &&
        Objects.equals(this.timestamp, jsonEntityAuditEventV2.timestamp) &&
        Objects.equals(this.type, jsonEntityAuditEventV2.type) &&
        Objects.equals(this.user, jsonEntityAuditEventV2.user);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action, details, entity, entityId, eventKey, timestamp, type, user);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonEntityAuditEventV2 {\n");
    
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    eventKey: ").append(toIndentedString(eventKey)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
