/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * class that captures details of an enum-type.
 */
@Schema(description = "class that captures details of an enum-type.")

public class JsonAtlasEnumDef extends JsonAtlasBaseTypeDef {
  @JsonProperty("defaultValue")
  private String defaultValue = null;

  @JsonProperty("elementDefs")
  private List<JsonAtlasEnumElementDef> elementDefs = null;

  public JsonAtlasEnumDef defaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
    return this;
  }

   /**
   * Get defaultValue
   * @return defaultValue
  **/
  @Schema(description = "")
  public String getDefaultValue() {
    return defaultValue;
  }

  public void setDefaultValue(String defaultValue) {
    this.defaultValue = defaultValue;
  }

  public JsonAtlasEnumDef elementDefs(List<JsonAtlasEnumElementDef> elementDefs) {
    this.elementDefs = elementDefs;
    return this;
  }

  public JsonAtlasEnumDef addElementDefsItem(JsonAtlasEnumElementDef elementDefsItem) {
    if (this.elementDefs == null) {
      this.elementDefs = new ArrayList<JsonAtlasEnumElementDef>();
    }
    this.elementDefs.add(elementDefsItem);
    return this;
  }

   /**
   * Get elementDefs
   * @return elementDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasEnumElementDef> getElementDefs() {
    return elementDefs;
  }

  public void setElementDefs(List<JsonAtlasEnumElementDef> elementDefs) {
    this.elementDefs = elementDefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEnumDef jsonAtlasEnumDef = (JsonAtlasEnumDef) o;
    return Objects.equals(this.defaultValue, jsonAtlasEnumDef.defaultValue) &&
        Objects.equals(this.elementDefs, jsonAtlasEnumDef.elementDefs) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultValue, elementDefs, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEnumDef {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    defaultValue: ").append(toIndentedString(defaultValue)).append("\n");
    sb.append("    elementDefs: ").append(toIndentedString(elementDefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
