/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonAtlasRelationshipWithExtInfo
 */


public class JsonAtlasRelationshipWithExtInfo {
  @JsonProperty("referredEntities")
  private Map<String, JsonAtlasEntityHeader> referredEntities = null;

  @JsonProperty("relationship")
  private JsonAtlasRelationship relationship = null;

  public JsonAtlasRelationshipWithExtInfo referredEntities(Map<String, JsonAtlasEntityHeader> referredEntities) {
    this.referredEntities = referredEntities;
    return this;
  }

  public JsonAtlasRelationshipWithExtInfo putReferredEntitiesItem(String key, JsonAtlasEntityHeader referredEntitiesItem) {
    if (this.referredEntities == null) {
      this.referredEntities = new HashMap<String, JsonAtlasEntityHeader>();
    }
    this.referredEntities.put(key, referredEntitiesItem);
    return this;
  }

   /**
   * Get referredEntities
   * @return referredEntities
  **/
  @Schema(description = "")
  public Map<String, JsonAtlasEntityHeader> getReferredEntities() {
    return referredEntities;
  }

  public void setReferredEntities(Map<String, JsonAtlasEntityHeader> referredEntities) {
    this.referredEntities = referredEntities;
  }

  public JsonAtlasRelationshipWithExtInfo relationship(JsonAtlasRelationship relationship) {
    this.relationship = relationship;
    return this;
  }

   /**
   * Get relationship
   * @return relationship
  **/
  @Schema(description = "")
  public JsonAtlasRelationship getRelationship() {
    return relationship;
  }

  public void setRelationship(JsonAtlasRelationship relationship) {
    this.relationship = relationship;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasRelationshipWithExtInfo jsonAtlasRelationshipWithExtInfo = (JsonAtlasRelationshipWithExtInfo) o;
    return Objects.equals(this.referredEntities, jsonAtlasRelationshipWithExtInfo.referredEntities) &&
        Objects.equals(this.relationship, jsonAtlasRelationshipWithExtInfo.relationship);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referredEntities, relationship);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasRelationshipWithExtInfo {\n");
    
    sb.append("    referredEntities: ").append(toIndentedString(referredEntities)).append("\n");
    sb.append("    relationship: ").append(toIndentedString(relationship)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
