/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.math.BigDecimal;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonAtlasFullTextResult
 */


public class JsonAtlasFullTextResult {
  @JsonProperty("entity")
  private JsonAtlasEntityHeader entity = null;

  @JsonProperty("score")
  private BigDecimal score = null;

  public JsonAtlasFullTextResult entity(JsonAtlasEntityHeader entity) {
    this.entity = entity;
    return this;
  }

   /**
   * Get entity
   * @return entity
  **/
  @Schema(description = "")
  public JsonAtlasEntityHeader getEntity() {
    return entity;
  }

  public void setEntity(JsonAtlasEntityHeader entity) {
    this.entity = entity;
  }

  public JsonAtlasFullTextResult score(BigDecimal score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @Schema(description = "")
  public BigDecimal getScore() {
    return score;
  }

  public void setScore(BigDecimal score) {
    this.score = score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasFullTextResult jsonAtlasFullTextResult = (JsonAtlasFullTextResult) o;
    return Objects.equals(this.entity, jsonAtlasFullTextResult.entity) &&
        Objects.equals(this.score, jsonAtlasFullTextResult.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entity, score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasFullTextResult {\n");
    
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
