/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * class that captures details of a struct-type.
 */
@Schema(description = "class that captures details of a struct-type.")

public class JsonAtlasStructDef extends JsonAtlasBaseTypeDef {
  @JsonProperty("attributeDefs")
  private List<JsonAtlasAttributeDef> attributeDefs = null;

  public JsonAtlasStructDef attributeDefs(List<JsonAtlasAttributeDef> attributeDefs) {
    this.attributeDefs = attributeDefs;
    return this;
  }

  public JsonAtlasStructDef addAttributeDefsItem(JsonAtlasAttributeDef attributeDefsItem) {
    if (this.attributeDefs == null) {
      this.attributeDefs = new ArrayList<JsonAtlasAttributeDef>();
    }
    this.attributeDefs.add(attributeDefsItem);
    return this;
  }
  
  public JsonAtlasStructDef addAttributeDefsItem(List<JsonAtlasAttributeDef> attributeDefsItems) {
    if (this.attributeDefs == null) {
      this.attributeDefs = attributeDefsItems;
    }
    this.attributeDefs.addAll(attributeDefsItems);
    return this;
  }

   /**
   * Get attributeDefs
   * @return attributeDefs
  **/
  @Schema(description = "")
  protected List<JsonAtlasAttributeDef> getAttributeDefs() {
    return attributeDefs;
  }

  protected void setAttributeDefs(List<JsonAtlasAttributeDef> attributeDefs) {
    this.attributeDefs = attributeDefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasStructDef jsonAtlasStructDef = (JsonAtlasStructDef) o;
    return Objects.equals(this.attributeDefs, jsonAtlasStructDef.attributeDefs) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeDefs, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasStructDef {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    attributeDefs: ").append(toIndentedString(attributeDefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
