/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonEntityMutationResponse
 */


public class JsonEntityMutationResponse {
  @JsonProperty("guidAssignments")
  private Map<String, String> guidAssignments = null;

  @JsonProperty("mutatedEntities")
  private Map<String, List<JsonAtlasEntityHeader>> mutatedEntities = null;

  @JsonProperty("partialUpdatedEntities")
  private List<JsonAtlasEntityHeader> partialUpdatedEntities = null;

  public JsonEntityMutationResponse guidAssignments(Map<String, String> guidAssignments) {
    this.guidAssignments = guidAssignments;
    return this;
  }

  public JsonEntityMutationResponse putGuidAssignmentsItem(String key, String guidAssignmentsItem) {
    if (this.guidAssignments == null) {
      this.guidAssignments = new HashMap<String, String>();
    }
    this.guidAssignments.put(key, guidAssignmentsItem);
    return this;
  }

   /**
   * Get guidAssignments
   * @return guidAssignments
  **/
  @Schema(description = "")
  public Map<String, String> getGuidAssignments() {
    return guidAssignments;
  }

  public void setGuidAssignments(Map<String, String> guidAssignments) {
    this.guidAssignments = guidAssignments;
  }

  public JsonEntityMutationResponse mutatedEntities(Map<String, List<JsonAtlasEntityHeader>> mutatedEntities) {
    this.mutatedEntities = mutatedEntities;
    return this;
  }

  public JsonEntityMutationResponse putMutatedEntitiesItem(String key, List<JsonAtlasEntityHeader> mutatedEntitiesItem) {
    if (this.mutatedEntities == null) {
      this.mutatedEntities = new HashMap<String, List<JsonAtlasEntityHeader>>();
    }
    this.mutatedEntities.put(key, mutatedEntitiesItem);
    return this;
  }

   /**
   * Get mutatedEntities
   * @return mutatedEntities
  **/
  @Schema(description = "")
  public Map<String, List<JsonAtlasEntityHeader>> getMutatedEntities() {
    return mutatedEntities;
  }

  public void setMutatedEntities(Map<String, List<JsonAtlasEntityHeader>> mutatedEntities) {
    this.mutatedEntities = mutatedEntities;
  }

  public JsonEntityMutationResponse partialUpdatedEntities(List<JsonAtlasEntityHeader> partialUpdatedEntities) {
    this.partialUpdatedEntities = partialUpdatedEntities;
    return this;
  }

  public JsonEntityMutationResponse addPartialUpdatedEntitiesItem(JsonAtlasEntityHeader partialUpdatedEntitiesItem) {
    if (this.partialUpdatedEntities == null) {
      this.partialUpdatedEntities = new ArrayList<JsonAtlasEntityHeader>();
    }
    this.partialUpdatedEntities.add(partialUpdatedEntitiesItem);
    return this;
  }

   /**
   * Get partialUpdatedEntities
   * @return partialUpdatedEntities
  **/
  @Schema(description = "")
  public List<JsonAtlasEntityHeader> getPartialUpdatedEntities() {
    return partialUpdatedEntities;
  }

  public void setPartialUpdatedEntities(List<JsonAtlasEntityHeader> partialUpdatedEntities) {
    this.partialUpdatedEntities = partialUpdatedEntities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonEntityMutationResponse jsonEntityMutationResponse = (JsonEntityMutationResponse) o;
    return Objects.equals(this.guidAssignments, jsonEntityMutationResponse.guidAssignments) &&
        Objects.equals(this.mutatedEntities, jsonEntityMutationResponse.mutatedEntities) &&
        Objects.equals(this.partialUpdatedEntities, jsonEntityMutationResponse.partialUpdatedEntities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guidAssignments, mutatedEntities, partialUpdatedEntities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonEntityMutationResponse {\n");
    
    sb.append("    guidAssignments: ").append(toIndentedString(guidAssignments)).append("\n");
    sb.append("    mutatedEntities: ").append(toIndentedString(mutatedEntities)).append("\n");
    sb.append("    partialUpdatedEntities: ").append(toIndentedString(partialUpdatedEntities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
