/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * An instance of an entity along with extended info - like hive_table, hive_database.
 */
@Schema(description = "An instance of an entity along with extended info - like hive_table, hive_database.")

public class JsonAtlasEntitiesWithExtInfo extends JsonAtlasEntityExtInfo {
  @JsonProperty("entities")
  private List<JsonAtlasEntity> entities = null;

  public JsonAtlasEntitiesWithExtInfo entities(List<JsonAtlasEntity> entities) {
    this.entities = entities;
    return this;
  }

  public JsonAtlasEntitiesWithExtInfo addEntitiesItem(JsonAtlasEntity entitiesItem) {
    if (this.entities == null) {
      this.entities = new ArrayList<JsonAtlasEntity>();
    }
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * Get entities
   * @return entities
  **/
  @Schema(description = "")
  public List<JsonAtlasEntity> getEntities() {
    return entities;
  }

  public void setEntities(List<JsonAtlasEntity> entities) {
    this.entities = entities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEntitiesWithExtInfo jsonAtlasEntitiesWithExtInfo = (JsonAtlasEntitiesWithExtInfo) o;
    return Objects.equals(this.entities, jsonAtlasEntitiesWithExtInfo.entities) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entities, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEntitiesWithExtInfo {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
