/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets json_EntityAuditActionV2
 */
public enum JsonEntityAuditActionV2 {
  ENTITY_CREATE("ENTITY_CREATE"),
  ENTITY_UPDATE("ENTITY_UPDATE"),
  ENTITY_DELETE("ENTITY_DELETE"),
  ENTITY_IMPORT_CREATE("ENTITY_IMPORT_CREATE"),
  ENTITY_IMPORT_UPDATE("ENTITY_IMPORT_UPDATE"),
  ENTITY_IMPORT_DELETE("ENTITY_IMPORT_DELETE"),
  CLASSIFICATION_ADD("CLASSIFICATION_ADD"),
  CLASSIFICATION_DELETE("CLASSIFICATION_DELETE"),
  CLASSIFICATION_UPDATE("CLASSIFICATION_UPDATE"),
  PROPAGATED_CLASSIFICATION_ADD("PROPAGATED_CLASSIFICATION_ADD"),
  PROPAGATED_CLASSIFICATION_DELETE("PROPAGATED_CLASSIFICATION_DELETE"),
  PROPAGATED_CLASSIFICATION_UPDATE("PROPAGATED_CLASSIFICATION_UPDATE"),
  TERM_ADD("TERM_ADD"),
  TERM_DELETE("TERM_DELETE"),
  LABEL_ADD("LABEL_ADD"),
  LABEL_DELETE("LABEL_DELETE"),
  ENTITY_PURGE("ENTITY_PURGE"),
  BUSINESS_ATTRIBUTE_UPDATE("BUSINESS_ATTRIBUTE_UPDATE");

  private String value;

  JsonEntityAuditActionV2(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static JsonEntityAuditActionV2 fromValue(String text) {
    for (JsonEntityAuditActionV2 b : JsonEntityAuditActionV2.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
