/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * An instance of an entity along with extended info - like hive_table, hive_database.
 */
@Schema(description = "An instance of an entity along with extended info - like hive_table, hive_database.")

public class JsonAtlasEntityExtInfo {
  @JsonProperty("referredEntities")
  private Map<String, JsonAtlasEntity> referredEntities = null;

  public JsonAtlasEntityExtInfo referredEntities(Map<String, JsonAtlasEntity> referredEntities) {
    this.referredEntities = referredEntities;
    return this;
  }

  public JsonAtlasEntityExtInfo putReferredEntitiesItem(String key, JsonAtlasEntity referredEntitiesItem) {
    if (this.referredEntities == null) {
      this.referredEntities = new HashMap<String, JsonAtlasEntity>();
    }
    this.referredEntities.put(key, referredEntitiesItem);
    return this;
  }

   /**
   * Get referredEntities
   * @return referredEntities
  **/
  @Schema(description = "")
  public Map<String, JsonAtlasEntity> getReferredEntities() {
    return referredEntities;
  }

  public void setReferredEntities(Map<String, JsonAtlasEntity> referredEntities) {
    this.referredEntities = referredEntities;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEntityExtInfo jsonAtlasEntityExtInfo = (JsonAtlasEntityExtInfo) o;
    return Objects.equals(this.referredEntities, jsonAtlasEntityExtInfo.referredEntities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referredEntities);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEntityExtInfo {\n");
    
    sb.append("    referredEntities: ").append(toIndentedString(referredEntities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
