/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonAtlasTypesDef
 */


public class JsonAtlasTypesDef {
  @JsonProperty("businessMetadataDefs")
  private List<JsonAtlasBusinessMetadataDef> businessMetadataDefs = null;

  @JsonProperty("classificationDefs")
  private List<JsonAtlasClassificationDef> classificationDefs = null;

  @JsonProperty("entityDefs")
  private List<JsonAtlasEntityDef> entityDefs = null;

  @JsonProperty("enumDefs")
  private List<JsonAtlasEnumDef> enumDefs = null;

  @JsonProperty("relationshipDefs")
  private List<JsonAtlasRelationshipDef> relationshipDefs = null;

  @JsonProperty("structDefs")
  private List<JsonAtlasStructDef> structDefs = null;

  public JsonAtlasTypesDef businessMetadataDefs(List<JsonAtlasBusinessMetadataDef> businessMetadataDefs) {
    this.businessMetadataDefs = businessMetadataDefs;
    return this;
  }

  public JsonAtlasTypesDef addBusinessMetadataDefsItem(JsonAtlasBusinessMetadataDef businessMetadataDefsItem) {
    if (this.businessMetadataDefs == null) {
      this.businessMetadataDefs = new ArrayList<JsonAtlasBusinessMetadataDef>();
    }
    this.businessMetadataDefs.add(businessMetadataDefsItem);
    return this;
  }

   /**
   * Get businessMetadataDefs
   * @return businessMetadataDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasBusinessMetadataDef> getBusinessMetadataDefs() {
    return businessMetadataDefs;
  }

  public void setBusinessMetadataDefs(List<JsonAtlasBusinessMetadataDef> businessMetadataDefs) {
    this.businessMetadataDefs = businessMetadataDefs;
  }

  public JsonAtlasTypesDef classificationDefs(List<JsonAtlasClassificationDef> classificationDefs) {
    this.classificationDefs = classificationDefs;
    return this;
  }

  public JsonAtlasTypesDef addClassificationDefsItem(JsonAtlasClassificationDef classificationDefsItem) {
    if (this.classificationDefs == null) {
      this.classificationDefs = new ArrayList<JsonAtlasClassificationDef>();
    }
    this.classificationDefs.add(classificationDefsItem);
    return this;
  }

   /**
   * Get classificationDefs
   * @return classificationDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasClassificationDef> getClassificationDefs() {
    return classificationDefs;
  }

  public void setClassificationDefs(List<JsonAtlasClassificationDef> classificationDefs) {
    this.classificationDefs = classificationDefs;
  }

  public JsonAtlasTypesDef entityDefs(List<JsonAtlasEntityDef> entityDefs) {
    this.entityDefs = entityDefs;
    return this;
  }

  public JsonAtlasTypesDef addEntityDefsItem(JsonAtlasEntityDef entityDefsItem) {
    if (this.entityDefs == null) {
      this.entityDefs = new ArrayList<JsonAtlasEntityDef>();
    }
    this.entityDefs.add(entityDefsItem);
    return this;
  }

   /**
   * Get entityDefs
   * @return entityDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasEntityDef> getEntityDefs() {
    return entityDefs;
  }

  public void setEntityDefs(List<JsonAtlasEntityDef> entityDefs) {
    this.entityDefs = entityDefs;
  }

  public JsonAtlasTypesDef enumDefs(List<JsonAtlasEnumDef> enumDefs) {
    this.enumDefs = enumDefs;
    return this;
  }

  public JsonAtlasTypesDef addEnumDefsItem(JsonAtlasEnumDef enumDefsItem) {
    if (this.enumDefs == null) {
      this.enumDefs = new ArrayList<JsonAtlasEnumDef>();
    }
    this.enumDefs.add(enumDefsItem);
    return this;
  }

   /**
   * Get enumDefs
   * @return enumDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasEnumDef> getEnumDefs() {
    return enumDefs;
  }

  public void setEnumDefs(List<JsonAtlasEnumDef> enumDefs) {
    this.enumDefs = enumDefs;
  }

  public JsonAtlasTypesDef relationshipDefs(List<JsonAtlasRelationshipDef> relationshipDefs) {
    this.relationshipDefs = relationshipDefs;
    return this;
  }

  public JsonAtlasTypesDef addRelationshipDefsItem(JsonAtlasRelationshipDef relationshipDefsItem) {
    if (this.relationshipDefs == null) {
      this.relationshipDefs = new ArrayList<JsonAtlasRelationshipDef>();
    }
    this.relationshipDefs.add(relationshipDefsItem);
    return this;
  }

   /**
   * Get relationshipDefs
   * @return relationshipDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasRelationshipDef> getRelationshipDefs() {
    return relationshipDefs;
  }

  public void setRelationshipDefs(List<JsonAtlasRelationshipDef> relationshipDefs) {
    this.relationshipDefs = relationshipDefs;
  }

  public JsonAtlasTypesDef structDefs(List<JsonAtlasStructDef> structDefs) {
    this.structDefs = structDefs;
    return this;
  }

  public JsonAtlasTypesDef addStructDefsItem(JsonAtlasStructDef structDefsItem) {
    if (this.structDefs == null) {
      this.structDefs = new ArrayList<JsonAtlasStructDef>();
    }
    this.structDefs.add(structDefsItem);
    return this;
  }

   /**
   * Get structDefs
   * @return structDefs
  **/
  @Schema(description = "")
  public List<JsonAtlasStructDef> getStructDefs() {
    return structDefs;
  }

  public void setStructDefs(List<JsonAtlasStructDef> structDefs) {
    this.structDefs = structDefs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasTypesDef jsonAtlasTypesDef = (JsonAtlasTypesDef) o;
    return Objects.equals(this.businessMetadataDefs, jsonAtlasTypesDef.businessMetadataDefs) &&
        Objects.equals(this.classificationDefs, jsonAtlasTypesDef.classificationDefs) &&
        Objects.equals(this.entityDefs, jsonAtlasTypesDef.entityDefs) &&
        Objects.equals(this.enumDefs, jsonAtlasTypesDef.enumDefs) &&
        Objects.equals(this.relationshipDefs, jsonAtlasTypesDef.relationshipDefs) &&
        Objects.equals(this.structDefs, jsonAtlasTypesDef.structDefs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessMetadataDefs, classificationDefs, entityDefs, enumDefs, relationshipDefs, structDefs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasTypesDef {\n");
    
    sb.append("    businessMetadataDefs: ").append(toIndentedString(businessMetadataDefs)).append("\n");
    sb.append("    classificationDefs: ").append(toIndentedString(classificationDefs)).append("\n");
    sb.append("    entityDefs: ").append(toIndentedString(entityDefs)).append("\n");
    sb.append("    enumDefs: ").append(toIndentedString(enumDefs)).append("\n");
    sb.append("    relationshipDefs: ").append(toIndentedString(relationshipDefs)).append("\n");
    sb.append("    structDefs: ").append(toIndentedString(structDefs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
