/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * Reference to an object-instance of AtlasEntity type used in relationship attribute values
 */
@Schema(description = "Reference to an object-instance of AtlasEntity type used in relationship attribute values")

public class JsonAtlasRelatedObjectId extends JsonAtlasObjectId {
  @JsonProperty("displayText")
  private String displayText = null;

  @JsonProperty("entityStatus")
  private JsonStatus entityStatus = null;

  @JsonProperty("relationshipAttributes")
  private JsonAtlasStruct relationshipAttributes = null;

  @JsonProperty("relationshipGuid")
  private String relationshipGuid = null;

  @JsonProperty("relationshipStatus")
  private JsonStatusAtlasRelationship relationshipStatus = null;

  @JsonProperty("relationshipType")
  private String relationshipType = null;

  public JsonAtlasRelatedObjectId displayText(String displayText) {
    this.displayText = displayText;
    return this;
  }

   /**
   * Get displayText
   * @return displayText
  **/
  @Schema(description = "")
  public String getDisplayText() {
    return displayText;
  }

  public void setDisplayText(String displayText) {
    this.displayText = displayText;
  }

  public JsonAtlasRelatedObjectId entityStatus(JsonStatus entityStatus) {
    this.entityStatus = entityStatus;
    return this;
  }

   /**
   * Get entityStatus
   * @return entityStatus
  **/
  @Schema(description = "")
  public JsonStatus getEntityStatus() {
    return entityStatus;
  }

  public void setEntityStatus(JsonStatus entityStatus) {
    this.entityStatus = entityStatus;
  }

  public JsonAtlasRelatedObjectId relationshipAttributes(JsonAtlasStruct relationshipAttributes) {
    this.relationshipAttributes = relationshipAttributes;
    return this;
  }

   /**
   * Get relationshipAttributes
   * @return relationshipAttributes
  **/
  @Schema(description = "")
  public JsonAtlasStruct getRelationshipAttributes() {
    return relationshipAttributes;
  }

  public void setRelationshipAttributes(JsonAtlasStruct relationshipAttributes) {
    this.relationshipAttributes = relationshipAttributes;
  }

  public JsonAtlasRelatedObjectId relationshipGuid(String relationshipGuid) {
    this.relationshipGuid = relationshipGuid;
    return this;
  }

   /**
   * Get relationshipGuid
   * @return relationshipGuid
  **/
  @Schema(description = "")
  public String getRelationshipGuid() {
    return relationshipGuid;
  }

  public void setRelationshipGuid(String relationshipGuid) {
    this.relationshipGuid = relationshipGuid;
  }

  public JsonAtlasRelatedObjectId relationshipStatus(JsonStatusAtlasRelationship relationshipStatus) {
    this.relationshipStatus = relationshipStatus;
    return this;
  }

   /**
   * Get relationshipStatus
   * @return relationshipStatus
  **/
  @Schema(description = "")
  public JsonStatusAtlasRelationship getRelationshipStatus() {
    return relationshipStatus;
  }

  public void setRelationshipStatus(JsonStatusAtlasRelationship relationshipStatus) {
    this.relationshipStatus = relationshipStatus;
  }

  public JsonAtlasRelatedObjectId relationshipType(String relationshipType) {
    this.relationshipType = relationshipType;
    return this;
  }

   /**
   * Get relationshipType
   * @return relationshipType
  **/
  @Schema(description = "")
  public String getRelationshipType() {
    return relationshipType;
  }

  public void setRelationshipType(String relationshipType) {
    this.relationshipType = relationshipType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasRelatedObjectId jsonAtlasRelatedObjectId = (JsonAtlasRelatedObjectId) o;
    return Objects.equals(this.displayText, jsonAtlasRelatedObjectId.displayText) &&
        Objects.equals(this.entityStatus, jsonAtlasRelatedObjectId.entityStatus) &&
        Objects.equals(this.relationshipAttributes, jsonAtlasRelatedObjectId.relationshipAttributes) &&
        Objects.equals(this.relationshipGuid, jsonAtlasRelatedObjectId.relationshipGuid) &&
        Objects.equals(this.relationshipStatus, jsonAtlasRelatedObjectId.relationshipStatus) &&
        Objects.equals(this.relationshipType, jsonAtlasRelatedObjectId.relationshipType) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayText, entityStatus, relationshipAttributes, relationshipGuid, relationshipStatus, relationshipType, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasRelatedObjectId {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    displayText: ").append(toIndentedString(displayText)).append("\n");
    sb.append("    entityStatus: ").append(toIndentedString(entityStatus)).append("\n");
    sb.append("    relationshipAttributes: ").append(toIndentedString(relationshipAttributes)).append("\n");
    sb.append("    relationshipGuid: ").append(toIndentedString(relationshipGuid)).append("\n");
    sb.append("    relationshipStatus: ").append(toIndentedString(relationshipStatus)).append("\n");
    sb.append("    relationshipType: ").append(toIndentedString(relationshipType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
