/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets json_TypeCategory
 */
public enum JsonTypeCategory {
  PRIMITIVE("PRIMITIVE"),
  OBJECT_ID_TYPE("OBJECT_ID_TYPE"),
  ENUM("ENUM"),
  STRUCT("STRUCT"),
  CLASSIFICATION("CLASSIFICATION"),
  ENTITY("ENTITY"),
  ARRAY("ARRAY"),
  MAP("MAP"),
  RELATIONSHIP("RELATIONSHIP"),
  BUSINESS_METADATA("BUSINESS_METADATA");

  private String value;

  JsonTypeCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static JsonTypeCategory fromValue(String text) {
    for (JsonTypeCategory b : JsonTypeCategory.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
