/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonAtlasGlossaryHeader
 */


public class JsonAtlasGlossaryHeader {
  @JsonProperty("displayText")
  private String displayText = null;

  @JsonProperty("glossaryGuid")
  private String glossaryGuid = null;

  @JsonProperty("relationGuid")
  private String relationGuid = null;

  public JsonAtlasGlossaryHeader displayText(String displayText) {
    this.displayText = displayText;
    return this;
  }

   /**
   * Get displayText
   * @return displayText
  **/
  @Schema(description = "")
  public String getDisplayText() {
    return displayText;
  }

  public void setDisplayText(String displayText) {
    this.displayText = displayText;
  }

  public JsonAtlasGlossaryHeader glossaryGuid(String glossaryGuid) {
    this.glossaryGuid = glossaryGuid;
    return this;
  }

   /**
   * Get glossaryGuid
   * @return glossaryGuid
  **/
  @Schema(description = "")
  public String getGlossaryGuid() {
    return glossaryGuid;
  }

  public void setGlossaryGuid(String glossaryGuid) {
    this.glossaryGuid = glossaryGuid;
  }

  public JsonAtlasGlossaryHeader relationGuid(String relationGuid) {
    this.relationGuid = relationGuid;
    return this;
  }

   /**
   * Get relationGuid
   * @return relationGuid
  **/
  @Schema(description = "")
  public String getRelationGuid() {
    return relationGuid;
  }

  public void setRelationGuid(String relationGuid) {
    this.relationGuid = relationGuid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasGlossaryHeader jsonAtlasGlossaryHeader = (JsonAtlasGlossaryHeader) o;
    return Objects.equals(this.displayText, jsonAtlasGlossaryHeader.displayText) &&
        Objects.equals(this.glossaryGuid, jsonAtlasGlossaryHeader.glossaryGuid) &&
        Objects.equals(this.relationGuid, jsonAtlasGlossaryHeader.relationGuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayText, glossaryGuid, relationGuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasGlossaryHeader {\n");
    
    sb.append("    displayText: ").append(toIndentedString(displayText)).append("\n");
    sb.append("    glossaryGuid: ").append(toIndentedString(glossaryGuid)).append("\n");
    sb.append("    relationGuid: ").append(toIndentedString(relationGuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
