/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * class that captures details of a struct-attribute.
 */
@Schema(description = "class that captures details of a struct-attribute.")

public class JsonAtlasRelationshipAttributeDef extends JsonAtlasAttributeDef {
  @JsonProperty("isLegacyAttribute")
  private Boolean isLegacyAttribute = null;

  @JsonProperty("relationshipTypeName")
  private String relationshipTypeName = null;

  public JsonAtlasRelationshipAttributeDef isLegacyAttribute(Boolean isLegacyAttribute) {
    this.isLegacyAttribute = isLegacyAttribute;
    return this;
  }

   /**
   * Get isLegacyAttribute
   * @return isLegacyAttribute
  **/
  @Schema(description = "")
  public Boolean isIsLegacyAttribute() {
    return isLegacyAttribute;
  }

  public void setIsLegacyAttribute(Boolean isLegacyAttribute) {
    this.isLegacyAttribute = isLegacyAttribute;
  }

  public JsonAtlasRelationshipAttributeDef relationshipTypeName(String relationshipTypeName) {
    this.relationshipTypeName = relationshipTypeName;
    return this;
  }

   /**
   * Get relationshipTypeName
   * @return relationshipTypeName
  **/
  @Schema(description = "")
  public String getRelationshipTypeName() {
    return relationshipTypeName;
  }

  public void setRelationshipTypeName(String relationshipTypeName) {
    this.relationshipTypeName = relationshipTypeName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasRelationshipAttributeDef jsonAtlasRelationshipAttributeDef = (JsonAtlasRelationshipAttributeDef) o;
    return Objects.equals(this.isLegacyAttribute, jsonAtlasRelationshipAttributeDef.isLegacyAttribute) &&
        Objects.equals(this.relationshipTypeName, jsonAtlasRelationshipAttributeDef.relationshipTypeName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isLegacyAttribute, relationshipTypeName, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasRelationshipAttributeDef {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    isLegacyAttribute: ").append(toIndentedString(isLegacyAttribute)).append("\n");
    sb.append("    relationshipTypeName: ").append(toIndentedString(relationshipTypeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
