/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * An instance of a classification; it doesn&#x27;t have an identity, this object exists only when associated with an entity.
 */
@Schema(description = "An instance of a classification; it doesn't have an identity, this object exists only when associated with an entity.")

public class JsonAtlasClassification extends JsonAtlasStruct {
  @JsonProperty("entityGuid")
  private String entityGuid = null;

  @JsonProperty("entityStatus")
  private JsonStatus entityStatus = null;

  @JsonProperty("propagate")
  private Boolean propagate = null;

  @JsonProperty("removePropagationsOnEntityDelete")
  private Boolean removePropagationsOnEntityDelete = null;

  @JsonProperty("validityPeriods")
  private List<JsonTimeBoundary> validityPeriods = null;

  public JsonAtlasClassification entityGuid(String entityGuid) {
    this.entityGuid = entityGuid;
    return this;
  }

   /**
   * Get entityGuid
   * @return entityGuid
  **/
  @Schema(description = "")
  public String getEntityGuid() {
    return entityGuid;
  }

  public void setEntityGuid(String entityGuid) {
    this.entityGuid = entityGuid;
  }

  public JsonAtlasClassification entityStatus(JsonStatus entityStatus) {
    this.entityStatus = entityStatus;
    return this;
  }

   /**
   * Get entityStatus
   * @return entityStatus
  **/
  @Schema(description = "")
  public JsonStatus getEntityStatus() {
    return entityStatus;
  }

  public void setEntityStatus(JsonStatus entityStatus) {
    this.entityStatus = entityStatus;
  }

  public JsonAtlasClassification propagate(Boolean propagate) {
    this.propagate = propagate;
    return this;
  }

   /**
   * Get propagate
   * @return propagate
  **/
  @Schema(description = "")
  public Boolean isPropagate() {
    return propagate;
  }

  public void setPropagate(Boolean propagate) {
    this.propagate = propagate;
  }

  public JsonAtlasClassification removePropagationsOnEntityDelete(Boolean removePropagationsOnEntityDelete) {
    this.removePropagationsOnEntityDelete = removePropagationsOnEntityDelete;
    return this;
  }

   /**
   * Get removePropagationsOnEntityDelete
   * @return removePropagationsOnEntityDelete
  **/
  @Schema(description = "")
  public Boolean isRemovePropagationsOnEntityDelete() {
    return removePropagationsOnEntityDelete;
  }

  public void setRemovePropagationsOnEntityDelete(Boolean removePropagationsOnEntityDelete) {
    this.removePropagationsOnEntityDelete = removePropagationsOnEntityDelete;
  }

  public JsonAtlasClassification validityPeriods(List<JsonTimeBoundary> validityPeriods) {
    this.validityPeriods = validityPeriods;
    return this;
  }

  public JsonAtlasClassification addValidityPeriodsItem(JsonTimeBoundary validityPeriodsItem) {
    if (this.validityPeriods == null) {
      this.validityPeriods = new ArrayList<JsonTimeBoundary>();
    }
    this.validityPeriods.add(validityPeriodsItem);
    return this;
  }

   /**
   * Get validityPeriods
   * @return validityPeriods
  **/
  @Schema(description = "")
  public List<JsonTimeBoundary> getValidityPeriods() {
    return validityPeriods;
  }

  public void setValidityPeriods(List<JsonTimeBoundary> validityPeriods) {
    this.validityPeriods = validityPeriods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasClassification jsonAtlasClassification = (JsonAtlasClassification) o;
    return Objects.equals(this.entityGuid, jsonAtlasClassification.entityGuid) &&
        Objects.equals(this.entityStatus, jsonAtlasClassification.entityStatus) &&
        Objects.equals(this.propagate, jsonAtlasClassification.propagate) &&
        Objects.equals(this.removePropagationsOnEntityDelete, jsonAtlasClassification.removePropagationsOnEntityDelete) &&
        Objects.equals(this.validityPeriods, jsonAtlasClassification.validityPeriods) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityGuid, entityStatus, propagate, removePropagationsOnEntityDelete, validityPeriods, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasClassification {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    entityGuid: ").append(toIndentedString(entityGuid)).append("\n");
    sb.append("    entityStatus: ").append(toIndentedString(entityStatus)).append("\n");
    sb.append("    propagate: ").append(toIndentedString(propagate)).append("\n");
    sb.append("    removePropagationsOnEntityDelete: ").append(toIndentedString(removePropagationsOnEntityDelete)).append("\n");
    sb.append("    validityPeriods: ").append(toIndentedString(validityPeriods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
