/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonAtlasQuickSearchResult
 */


public class JsonAtlasQuickSearchResult {
  @JsonProperty("aggregationMetrics")
  private Map<String, List<JsonAtlasAggregationEntry>> aggregationMetrics = null;

  @JsonProperty("searchResults")
  private JsonAtlasSearchResult searchResults = null;

  public JsonAtlasQuickSearchResult aggregationMetrics(Map<String, List<JsonAtlasAggregationEntry>> aggregationMetrics) {
    this.aggregationMetrics = aggregationMetrics;
    return this;
  }

  public JsonAtlasQuickSearchResult putAggregationMetricsItem(String key, List<JsonAtlasAggregationEntry> aggregationMetricsItem) {
    if (this.aggregationMetrics == null) {
      this.aggregationMetrics = new HashMap<String, List<JsonAtlasAggregationEntry>>();
    }
    this.aggregationMetrics.put(key, aggregationMetricsItem);
    return this;
  }

   /**
   * Get aggregationMetrics
   * @return aggregationMetrics
  **/
  @Schema(description = "")
  public Map<String, List<JsonAtlasAggregationEntry>> getAggregationMetrics() {
    return aggregationMetrics;
  }

  public void setAggregationMetrics(Map<String, List<JsonAtlasAggregationEntry>> aggregationMetrics) {
    this.aggregationMetrics = aggregationMetrics;
  }

  public JsonAtlasQuickSearchResult searchResults(JsonAtlasSearchResult searchResults) {
    this.searchResults = searchResults;
    return this;
  }

   /**
   * Get searchResults
   * @return searchResults
  **/
  @Schema(description = "")
  public JsonAtlasSearchResult getSearchResults() {
    return searchResults;
  }

  public void setSearchResults(JsonAtlasSearchResult searchResults) {
    this.searchResults = searchResults;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasQuickSearchResult jsonAtlasQuickSearchResult = (JsonAtlasQuickSearchResult) o;
    return Objects.equals(this.aggregationMetrics, jsonAtlasQuickSearchResult.aggregationMetrics) &&
        Objects.equals(this.searchResults, jsonAtlasQuickSearchResult.searchResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aggregationMetrics, searchResults);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasQuickSearchResult {\n");
    
    sb.append("    aggregationMetrics: ").append(toIndentedString(aggregationMetrics)).append("\n");
    sb.append("    searchResults: ").append(toIndentedString(searchResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
