/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonAtlasEntityHeaders
 */


public class JsonAtlasEntityHeaders {
  @JsonProperty("guidHeaderMap")
  private Map<String, JsonAtlasEntityHeader> guidHeaderMap = null;

  public JsonAtlasEntityHeaders guidHeaderMap(Map<String, JsonAtlasEntityHeader> guidHeaderMap) {
    this.guidHeaderMap = guidHeaderMap;
    return this;
  }

  public JsonAtlasEntityHeaders putGuidHeaderMapItem(String key, JsonAtlasEntityHeader guidHeaderMapItem) {
    if (this.guidHeaderMap == null) {
      this.guidHeaderMap = new HashMap<String, JsonAtlasEntityHeader>();
    }
    this.guidHeaderMap.put(key, guidHeaderMapItem);
    return this;
  }

   /**
   * Get guidHeaderMap
   * @return guidHeaderMap
  **/
  @Schema(description = "")
  public Map<String, JsonAtlasEntityHeader> getGuidHeaderMap() {
    return guidHeaderMap;
  }

  public void setGuidHeaderMap(Map<String, JsonAtlasEntityHeader> guidHeaderMap) {
    this.guidHeaderMap = guidHeaderMap;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonAtlasEntityHeaders jsonAtlasEntityHeaders = (JsonAtlasEntityHeaders) o;
    return Objects.equals(this.guidHeaderMap, jsonAtlasEntityHeaders.guidHeaderMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(guidHeaderMap);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonAtlasEntityHeaders {\n");
    
    sb.append("    guidHeaderMap: ").append(toIndentedString(guidHeaderMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
