/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonBulkImportResponse
 */


public class JsonBulkImportResponse {
  @JsonProperty("failedImportInfoList")
  private List<JsonImportInfo> failedImportInfoList = null;

  @JsonProperty("successImportInfoList")
  private List<JsonImportInfo> successImportInfoList = null;

  public JsonBulkImportResponse failedImportInfoList(List<JsonImportInfo> failedImportInfoList) {
    this.failedImportInfoList = failedImportInfoList;
    return this;
  }

  public JsonBulkImportResponse addFailedImportInfoListItem(JsonImportInfo failedImportInfoListItem) {
    if (this.failedImportInfoList == null) {
      this.failedImportInfoList = new ArrayList<JsonImportInfo>();
    }
    this.failedImportInfoList.add(failedImportInfoListItem);
    return this;
  }

   /**
   * Get failedImportInfoList
   * @return failedImportInfoList
  **/
  @Schema(description = "")
  public List<JsonImportInfo> getFailedImportInfoList() {
    return failedImportInfoList;
  }

  public void setFailedImportInfoList(List<JsonImportInfo> failedImportInfoList) {
    this.failedImportInfoList = failedImportInfoList;
  }

  public JsonBulkImportResponse successImportInfoList(List<JsonImportInfo> successImportInfoList) {
    this.successImportInfoList = successImportInfoList;
    return this;
  }

  public JsonBulkImportResponse addSuccessImportInfoListItem(JsonImportInfo successImportInfoListItem) {
    if (this.successImportInfoList == null) {
      this.successImportInfoList = new ArrayList<JsonImportInfo>();
    }
    this.successImportInfoList.add(successImportInfoListItem);
    return this;
  }

   /**
   * Get successImportInfoList
   * @return successImportInfoList
  **/
  @Schema(description = "")
  public List<JsonImportInfo> getSuccessImportInfoList() {
    return successImportInfoList;
  }

  public void setSuccessImportInfoList(List<JsonImportInfo> successImportInfoList) {
    this.successImportInfoList = successImportInfoList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonBulkImportResponse jsonBulkImportResponse = (JsonBulkImportResponse) o;
    return Objects.equals(this.failedImportInfoList, jsonBulkImportResponse.failedImportInfoList) &&
        Objects.equals(this.successImportInfoList, jsonBulkImportResponse.successImportInfoList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failedImportInfoList, successImportInfoList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonBulkImportResponse {\n");
    
    sb.append("    failedImportInfoList: ").append(toIndentedString(failedImportInfoList)).append("\n");
    sb.append("    successImportInfoList: ").append(toIndentedString(successImportInfoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
