/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonLineageRelation
 */


public class JsonLineageRelation {
  @JsonProperty("fromEntityId")
  private String fromEntityId = null;

  @JsonProperty("relationshipId")
  private String relationshipId = null;

  @JsonProperty("toEntityId")
  private String toEntityId = null;

  public JsonLineageRelation fromEntityId(String fromEntityId) {
    this.fromEntityId = fromEntityId;
    return this;
  }

   /**
   * Get fromEntityId
   * @return fromEntityId
  **/
  @Schema(description = "")
  public String getFromEntityId() {
    return fromEntityId;
  }

  public void setFromEntityId(String fromEntityId) {
    this.fromEntityId = fromEntityId;
  }

  public JsonLineageRelation relationshipId(String relationshipId) {
    this.relationshipId = relationshipId;
    return this;
  }

   /**
   * Get relationshipId
   * @return relationshipId
  **/
  @Schema(description = "")
  public String getRelationshipId() {
    return relationshipId;
  }

  public void setRelationshipId(String relationshipId) {
    this.relationshipId = relationshipId;
  }

  public JsonLineageRelation toEntityId(String toEntityId) {
    this.toEntityId = toEntityId;
    return this;
  }

   /**
   * Get toEntityId
   * @return toEntityId
  **/
  @Schema(description = "")
  public String getToEntityId() {
    return toEntityId;
  }

  public void setToEntityId(String toEntityId) {
    this.toEntityId = toEntityId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonLineageRelation jsonLineageRelation = (JsonLineageRelation) o;
    return Objects.equals(this.fromEntityId, jsonLineageRelation.fromEntityId) &&
        Objects.equals(this.relationshipId, jsonLineageRelation.relationshipId) &&
        Objects.equals(this.toEntityId, jsonLineageRelation.toEntityId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromEntityId, relationshipId, toEntityId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonLineageRelation {\n");
    
    sb.append("    fromEntityId: ").append(toIndentedString(fromEntityId)).append("\n");
    sb.append("    relationshipId: ").append(toIndentedString(relationshipId)).append("\n");
    sb.append("    toEntityId: ").append(toIndentedString(toEntityId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
