/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets json_Relation
 */
public enum JsonRelation {
  SEE_ALSO("SEE_ALSO"),
  SYNONYMS("SYNONYMS"),
  ANTONYMS("ANTONYMS"),
  PREFERRED_TO_TERMS("PREFERRED_TO_TERMS"),
  PREFERRED_TERMS("PREFERRED_TERMS"),
  REPLACEMENT_TERMS("REPLACEMENT_TERMS"),
  REPLACED_BY("REPLACED_BY"),
  TRANSLATION_TERMS("TRANSLATION_TERMS"),
  TRANSLATED_TERMS("TRANSLATED_TERMS"),
  ISA("ISA"),
  CLASSIFIES("CLASSIFIES"),
  VALID_VALUES("VALID_VALUES"),
  VALID_VALUES_FOR("VALID_VALUES_FOR");

  private String value;

  JsonRelation(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static JsonRelation fromValue(String text) {
    for (JsonRelation b : JsonRelation.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
