/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
/**
 * JsonClassificationAssociateRequest
 */


public class JsonClassificationAssociateRequest {
  @JsonProperty("classification")
  private JsonAtlasClassification classification = null;

  @JsonProperty("entityGuids")
  private List<String> entityGuids = null;

  public JsonClassificationAssociateRequest classification(JsonAtlasClassification classification) {
    this.classification = classification;
    return this;
  }

   /**
   * Get classification
   * @return classification
  **/
  @Schema(description = "")
  public JsonAtlasClassification getClassification() {
    return classification;
  }

  public void setClassification(JsonAtlasClassification classification) {
    this.classification = classification;
  }

  public JsonClassificationAssociateRequest entityGuids(List<String> entityGuids) {
    this.entityGuids = entityGuids;
    return this;
  }

  public JsonClassificationAssociateRequest addEntityGuidsItem(String entityGuidsItem) {
    if (this.entityGuids == null) {
      this.entityGuids = new ArrayList<String>();
    }
    this.entityGuids.add(entityGuidsItem);
    return this;
  }

   /**
   * Get entityGuids
   * @return entityGuids
  **/
  @Schema(description = "")
  public List<String> getEntityGuids() {
    return entityGuids;
  }

  public void setEntityGuids(List<String> entityGuids) {
    this.entityGuids = entityGuids;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JsonClassificationAssociateRequest jsonClassificationAssociateRequest = (JsonClassificationAssociateRequest) o;
    return Objects.equals(this.classification, jsonClassificationAssociateRequest.classification) &&
        Objects.equals(this.entityGuids, jsonClassificationAssociateRequest.entityGuids);
  }

  @Override
  public int hashCode() {
    return Objects.hash(classification, entityGuids);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JsonClassificationAssociateRequest {\n");
    
    sb.append("    classification: ").append(toIndentedString(classification)).append("\n");
    sb.append("    entityGuids: ").append(toIndentedString(entityGuids)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
