/*
 * Atlas REST API
 * Atlas exposes a variety of REST endpoints to work with types, entities, lineage and data discovery.
 *
 * OpenAPI spec version: 3.0.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.github.jasonqjc.atlas_v2_client.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The Relationship category determines the style of relationship around containment and lifecycle. UML terminology is used for the values. &lt;p&gt; ASSOCIATION is a relationship with no containment. &lt;br&gt; COMPOSITION and AGGREGATION are containment relationships. &lt;p&gt; The difference being in the lifecycles of the container and its children. In the COMPOSITION case, the children cannot exist without the container. For AGGREGATION, the life cycles of the container and children are totally independant.
 */
public enum JsonRelationshipCategory {
  ASSOCIATION("ASSOCIATION"),
  AGGREGATION("AGGREGATION"),
  COMPOSITION("COMPOSITION");

  private String value;

  JsonRelationshipCategory(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static JsonRelationshipCategory fromValue(String text) {
    for (JsonRelationshipCategory b : JsonRelationshipCategory.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
